POST http://localhost:8080/roundResult?roundId=1
%%%

# Duration: 31 ms
# URL: http://localhost:8080/roundResult?roundId=1

# HTTP/1.1 200

@Content-Length: 0
@Date: Wed, 17 Mar 2021 06:20:56 GMT
@Keep-Alive: timeout=60
@Connection: keep-alive

