GET http://localhost:8080/roundResult?roundId=1
%%%

# Duration: 42 ms
# URL: http://localhost:8080/roundResult?roundId=1

# HTTP/1.1 200

@Content-Type: application/json
@Transfer-Encoding: chunked
@Date: Wed, 17 Mar 2021 06:20:59 GMT
@Keep-Alive: timeout=60
@Connection: keep-alive

[
  {
    "position": 1,
    "firstName": "Kamil",
    "lastName": "Stoch",
    "countryCode": "POL",
    "distance": 129.5,
    "totalNote": 126.6
  },
  {
    "position": 2,
    "firstName": "Kamil",
    "lastName": "Stoch",
    "countryCode": "POL",
    "distance": 126.5,
    "totalNote": 126.5
  },
  {
    "position": 3,
    "firstName": "Kamil",
    "lastName": "Stoch",
    "countryCode": "POL",
    "distance": 129.0,
    "totalNote": 124.2
  },
  {
    "position": 4,
    "firstName": "Andrzej",
    "lastName": "Stękała",
    "countryCode": "POL",
    "distance": 129.0,
    "totalNote": 124.2
  },
  {
    "position": 5,
    "firstName": "Kamil",
    "lastName": "Stoch",
    "countryCode": "POL",
    "distance": 126.5,
    "totalNote": 121.3
  },
  {
    "position": 6,
    "firstName": "Kamil",
    "lastName": "Stoch",
    "countryCode": "POL",
    "distance": 124.5,
    "totalNote": 118.3
  },
  {
    "position": 7,
    "firstName": "Kamil",
    "lastName": "Stoch",
    "countryCode": "POL",
    "distance": 124.5,
    "totalNote": 118.3
  }
]