POST http://localhost:8080/competition/calculate
@Content-Type: application/json

{
  "kPoint": 125,
  "distance": 150,
  "juryNotes": [10, 10, 10, 15, 20],
  "gate": 0,
  "windSpeed": 0
}

%%%

# Duration: 334 ms
# URL: http://localhost:8080/competition/calculate

# HTTP/1.1 200

@Content-Type: application/json
@Transfer-Encoding: chunked
@Date: Thu, 11 Mar 2021 21:18:44 GMT
@Keep-Alive: timeout=60
@Connection: keep-alive

{
  "distanceNote": 780.0,
  "juryNote": 35,
  "additionalNote": 0,
  "totalNote": 815.0
}