POST http://localhost:8080/jump/official
@Content-Type: application/json

{
  "competitionId": 1,
  "distance": 136.5,
  "juryNotes": [18.5, 17, 18, 18, 18.5],
  "gate": 10,
  "windSpeed": -1.4
}

%%%

# Duration: 375 ms
# URL: http://localhost:8080/jump/official

# HTTP/1.1 200

@Content-Type: application/json
@Transfer-Encoding: chunked
@Date: Sun, 14 Mar 2021 19:03:38 GMT
@Keep-Alive: timeout=60
@Connection: keep-alive

{
  "distanceNote": 80.6,
  "juryNote": 54.5,
  "additionalNote": -7.2,
  "totalNote": 120.7
}