POST http://localhost:8080/jump/training
@Content-Type: application/json

{
  "baseGate": 12,
  "hillSize": 140,
  "kpoint": 125,
  "distance": 136.5,
  "juryNotes": [18.5, 17, 18, 18, 18.5],
  "gate": 10,
  "windSpeed": -1.4
}

%%%

# Duration: 328 ms
# URL: http://localhost:8080/jump/training

# HTTP/1.1 200

@Content-Type: application/json
@Transfer-Encoding: chunked
@Date: Fri, 12 Mar 2021 06:52:25 GMT
@Keep-Alive: timeout=60
@Connection: keep-alive

{
  "distanceNote": 80.6,
  "juryNote": 0,
  "additionalNote": 1.8,
  "totalNote": 75.2
}