POST http://localhost:8080/jump
Content-Type: application/json

{
  "competitionRoundId": 1,
  "distance": 136.5,
  "juryNotes": [
    {
        "judgeId": 1,
        "note": 18.5
    },
    {
        "judgeId": 2,
        "note": 18.5
    },
    {
        "judgeId": 3,
        "note": 18.5
    },
    {
        "judgeId": 4,
        "note": 18.0
    },
    {
        "judgeId": 5,
        "note": 18.5
    }
  ],
  "gate": 10,
  "windSpeed": -1.4
}
